[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -s --alluredir=allure-results --strict-markers
markers =
    android: 安卓端用例
    ios: iOS 端用例
    smoke: 冒烟测试
    regression: 回归测试
